name: Terraform Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configure SSH for Git operations
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
      # Iterate through each Terraform directory
      - name: Iterate through directories
        id: iterate-directories
        run: |
          for dir in $(find . -type d -name 'terraform'); do
            cd $dir
            echo "Entering directory $dir"
            
            # Initialize Terraform
            terraform init

            # Validate Terraform configuration
            terraform validate

            # Plan Terraform changes
            terraform plan -var-file=../variables/terraform.tfvars
            
            # Apply Terraform changes (auto-approve for automation)
            terraform apply -auto-approve -var-file=../variables/terraform.tfvars
            
            cd ..
          done

