name: Terraform Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

  workflow_dispatch:  # Allow manual trigger

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  terraform-iam-group-management:
    name: Terraform IAM Group Management
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Decode and set the SSH_PRIVATE_KEY environment variable
      - name: Decode and Set SSH_PRIVATE_KEY
        run: echo "SSH_PRIVATE_KEY=$(echo ${{ secrets.SSH_PRIVATE_KEY_ENCODED }} | base64 --decode)" >> $GITHUB_ENV

      # Configure SSH for Git operations
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::128333337075:role/GitHubActionRunner
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Initialize Terraform
        run: |
          cd iam_group_management/terraform
          terraform init

      - name: Validate Terraform Configuration
        run: |
          cd iam_group_management/terraform
          terraform validate

      - name: Plan Terraform Changes
        run: |
          cd iam_group_management/terraform
          terraform plan -var-file=../variables/terraform.tfvars