name: Terraform Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual trigger

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  terraform-init-plan:
    name: Run Terraform Init and Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configure SSH for Git operations
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::128333337075:role/GitHubActionRunner
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: aws sts get-caller-identity

      # Initialize and Plan Terraform iam_group_management
      - name: Init and Plan Terraform iam_group_management
        run: |
          cd iam_group_management/terraform
          terraform init
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

      # Initialize and Plan Terraform iam_identity_provider_management
      - name: Init and Plan Terraform iam_identity_provider_management
        run: |
          cd iam_identity_provider_management/terraform
          terraform init
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

      # Initialize and Plan Terraform iam_policy_management
      - name: Init and Plan Terraform iam_policy_management
        run: |
          cd iam_policy_management/terraform
          terraform init
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

      # Initialize and Plan Terraform iam_user_management
      - name: Init and Plan Terraform iam_user_management
        run: |
          cd iam_user_management/terraform
          terraform init
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

      # Initialize and Plan Terraform iam_role_management
      - name: Init and Plan Terraform iam_role_management
        run: |
          cd iam_role_management/terraform
          terraform init
          terraform validate
          terraform plan -var-file=../variables/terraform.tfvars

  terraform-apply-group:
    name: Apply Terraform iam_group_management
    runs-on: ubuntu-latest
    needs: terraform-init-plan
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configure SSH for Git operations
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::128333337075:role/GitHubActionRunner
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Apply Terraform iam_group_management
        run: |
          cd iam_group_management/terraform
          terraform apply -var-file=../variables/terraform.tfvars

  terraform-apply-identity-provider:
    name: Apply Terraform iam_identity_provider_management
    runs-on: ubuntu-latest
    needs: terraform-init-plan
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configure SSH for Git operations
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::128333337075:role/GitHubActionRunner
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Apply Terraform iam_identity_provider_management
        run: |
          cd iam_identity_provider_management/terraform
          terraform apply -var-file=../variables/terraform.tfvars

  terraform-apply-policy:
    name: Apply Terraform iam_policy_management
    runs-on: ubuntu-latest
    needs: terraform-init-plan
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configure SSH for Git operations
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::128333337075:role/GitHubActionRunner
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Apply Terraform iam_policy_management
        run: |
          cd iam_policy_management/terraform
          terraform apply -var-file=../variables/terraform.tfvars

  terraform-apply-user:
    name: Apply Terraform iam_user_management
    runs-on: ubuntu-latest
    needs: terraform-init-plan
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configure SSH for Git operations
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::128333337075:role/GitHubActionRunner
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Apply Terraform iam_user_management
        run: |
          cd iam_user_management/terraform
          terraform apply -var-file=../variables/terraform.tfvars

  terraform-apply-role:
    name: Apply Terraform iam_role_management
    runs-on: ubuntu-latest
    needs: terraform-init-plan
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configure SSH for Git operations
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::128333337075:role/GitHubActionRunner
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Apply Terraform iam_role_management
        run: |
          cd iam_role_management/terraform
          terraform apply -var-file=../variables/terraform.tfvars
